# Generated by Django 5.0.3 on 2024-03-21 21:06

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tea_id', models.IntegerField()),
                ('count', models.IntegerField(verbose_name='скока шт')),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название чая')),
                ('price', models.IntegerField(verbose_name='цена чая')),
                ('count', models.IntegerField(verbose_name='количество чая')),
                ('images', django_mysql.models.SizedTextField(size_class=3, verbose_name='изображение')),
            ],
        ),
    ]
